# Metody analizy danych. Lab 5. Biblioteka pandas, część 2

In [23]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# 1. Indeksowanie i wybieranie danych

O ile statystyki dla całej serii lub ramki danych są przydatne, o tyle często interesują nas różne podgrupy danych i ich własności co wymaga poznania (również poprzez analogię do poznanych już wycinków) mechanizmów pobierania i filtrowania danych w pandas. Najpierw załadujemy jednak niezbędne dane.

W poniższych przykładach należy zaktualizować ścieżkę do danych, tak aby odpowiadała lokalnej strukturze przechowywania plików.

In [24]:
import pandas as pd
import os

In [25]:
DATAPATH = './sample_data/DATA'

In [26]:
# dane pochdzą z serwisu Kaggle: https://www.kaggle.com/datasets/udaymalviya/bank-loan-data
df = pd.read_csv(os.path.join(DATAPATH, 'loan_data.csv'))

In [27]:
df.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

## 1.1 Proste wybieranie kolumn danych z ramki

In [28]:
# wybieramy dane z jednej kolumny
df['person_gender']

0        female
1        female
2        female
3        female
4          male
          ...
44995      male
44996    female
44997      male
44998      male
44999      male
Name: person_gender, Length: 45000, dtype: object

In [29]:
# w ten sam sposób możemy również wybrać dane z wielu kolumn, tym razem przekazujemy listę kolumn
df[['person_gender','person_education']]

      person_gender person_education
0            female           Master
1            female      High School
2            female      High School
3            female         Bachelor
4              male           Master
...             ...              ...
44995          male        Associate
44996        female        Associate
44997          male        Associate
44998          male         Bachelor
44999          male      High School

[45000 rows x 2 columns]

In [30]:
# możemy również odwołać się do danych w kolumnie poprzez operator kropki
# w zależności od tego czy nazwy kolumn zawierają białe znaki czy nie
df.person_gender

0        female
1        female
2        female
3        female
4          male
          ...
44995      male
44996    female
44997      male
44998      male
44999      male
Name: person_gender, Length: 45000, dtype: object

In [31]:
# pojedyncza kolumna to seria danych, tu możemy również podać indeks, lub wycinek
df['person_gender'][:5]

0    female
1    female
2    female
3    female
4      male
Name: person_gender, dtype: object

In [32]:
df[['person_gender','person_education']][:5]

  person_gender person_education
0        female           Master
1        female      High School
2        female      High School
3        female         Bachelor
4          male           Master

## 1.2 Wybieranie danych poprzez `.loc`, `.iloc` oraz mapowanie tablicą boolowską

`.loc` jest oparte o indeksowanie oparte na etykietach, ale można również przekazać tablice boolowską. Etykiety to inaczej wartości w kolumnie indeksu pandas series lub pandas data frame albo nazwy kolumn w pandas dataframe.

In [33]:
# dla ramki mamy dwa wymiary - wiersze oraz kolumny
df.loc[:, 'person_gender']

0        female
1        female
2        female
3        female
4          male
          ...
44995      male
44996    female
44997      male
44998      male
44999      male
Name: person_gender, Length: 45000, dtype: object

In [34]:
# możemy również podać wartość tylko w jednym wymiarze
# tu szukamy wierszy, które w kolumnie indeks mają wartości 1 lub 2 lub 3
df.loc[[1,2,3]]

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1

In [35]:
df.loc[:5, ['person_gender', 'person_income']]

  person_gender  person_income
0        female        71948.0
1        female        12282.0
2        female        12438.0
3        female        79753.0
4          male        66135.0
5        female        12951.0

In [36]:
# weźmy pod uwagę, że wartość dla pierwszego wymiaru loc to faktyczna wartość w kolumnie indeks
# a nie wartość indeksu elementów w tym indeksie
# poniżej przykład gdzie indeks został zmieniony na wartości rozpoczynające się od 1
df.index = range(1, df.shape[0] + 1)

In [37]:
df[:5]

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
1,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
2,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
3,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
4,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
5,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

In [38]:
# teraz sprawdzimy raz jeszcze jak działa loc z tymi samymi parametrami
df.loc[:5, ['person_gender', 'person_income']]

  person_gender  person_income
1        female        71948.0
2        female        12282.0
3        female        12438.0
4        female        79753.0
5          male        66135.0

**UWAGA!**

Indeksowanie poprzez etykiety wykonywane jest z włączeniem wartości stop, co jest odmienne od tego jak działają klasyczne wycinki w Pythonie!.

Indeksowanie przez `.iloc` jest podobne do `.loc`, ale tutaj litera `i` oznacza indeks, więc zamiast wartości etykiet kolumn oraz wierszy podajemy indeksy.

In [39]:
# indeksy wierszy 0-4, indeks kolumn 2 i 3
df.iloc[:5, 2:4]

  person_education  person_income
1           Master        71948.0
2      High School        12282.0
3      High School        12438.0
4         Bachelor        79753.0
5           Master        66135.0

In [40]:
# podobnie jak w przypadku biblioteki numpy możemy w tych obszarach również podstawiać dane, np. zamienić kolumny kolejnością
# chociaż nie jest to zazwyczaj konieczne, gdyż możemy pobierać dane z ramki w dowolnej kolejności kolumn
# pobieramy kolumny w dowolnej kolejności
df.iloc[:, [2,1, 3]]

      person_education person_gender  person_income
1               Master        female        71948.0
2          High School        female        12282.0
3          High School        female        12438.0
4             Bachelor        female        79753.0
5               Master          male        66135.0
...                ...           ...            ...
44996        Associate          male        47971.0
44997        Associate        female        65800.0
44998        Associate          male        56942.0
44999         Bachelor          male        33164.0
45000      High School          male        51609.0

[45000 rows x 3 columns]

In [41]:
# gdybyśmy jednak chcieli zamienić jes kolejnością w oryginalnej ramce to możemy np. wykorzystać do tego wektor
# aktualnych nazw kolumn z właściwości .columns
df.columns

Index(['person_age', 'person_gender', 'person_education', 'person_income',
       'person_emp_exp', 'person_home_ownership', 'loan_amnt', 'loan_intent',
       'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length',
       'credit_score', 'previous_loan_defaults_on_file', 'loan_status'],
      dtype='object')

In [42]:
# załóżmy, że chcemy zamienić miejscami kolumnę 2 i 3
# dla uproszczenia przechowamy wartości tych etykiet w liście Pythonowej
old_columns = list(df.columns)
new_column_order = old_columns[:1] + old_columns[2:0:-1] + old_columns[3:]
new_column_order

['person_age',
 'person_education',
 'person_gender',
 'person_income',
 'person_emp_exp',
 'person_home_ownership',
 'loan_amnt',
 'loan_intent',
 'loan_int_rate',
 'loan_percent_income',
 'cb_person_cred_hist_length',
 'credit_score',
 'previous_loan_defaults_on_file',
 'loan_status']

In [43]:
df = df.loc[:, new_column_order]

In [44]:
df.head()

,person_age,person_education,person_gender,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
1,22.0,Master,female,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
2,21.0,High School,female,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
3,25.0,High School,female,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
4,23.0,Bachelor,female,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
5,24.0,Master,male,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

**Wybieranie danych poprzez tablice wartości boolowskich**

Ta operacja jest zazwyczaj wykonywana w przypadku operacji filtrowania danych, gdzie nakładany jest warunek, na podstawie którego chcemy dane z ramki lub serii wybrać. Możemy tutaj wykorzystać operatory `|` (logiczne or), `&` (logiczne and) oraz `~` jako negację.

In [45]:
# zwracana jest tablica boolowska (tzw. mapowanie)
print(df['person_gender'] == 'female')

# teraz przykładamy mapowanie do danych poprzez przekazanie tego mapowania tak jak w przykładach wcześniejszych
df[df['person_gender'] == 'female']

1         True
2         True
3         True
4         True
5        False
         ...
44996    False
44997     True
44998    False
44999    False
45000    False
Name: person_gender, Length: 45000, dtype: bool

,person_age,person_education,person_gender,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
1,22.0,Master,female,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
2,21.0,High School,female,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
3,25.0,High School,female,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
4,23.0,Bachelor,female,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
6,21.0,High School,female,12951.0,0,OWN,2500.0,VENTURE,7.14,0.19,2.0,532,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44989,28.0,Associate,female,49170.0,4,RENT,10401.0,HOMEIMPROVEMENT,11.97,0.21,6.0,677,No,1
44993,23.0,Bachelor,female,40925.0,0,RENT,9000.0,PERSONAL,11.01,0.22,4.0,487,No,1
44994,27.0,High School,female,35512.0,4,RENT,5000.0,PERSONAL,15.83,0.14,5.0,505,No,1
44995,24.0,Associate,female,31924.0,2,RENT,12229.0,MEDICAL,10.70,0.38,4.0,678,No,1
44997,37.0,Associate,female,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1

In [46]:
# więcej warunków - tu znowu mapowanie
(df['loan_amnt'] > 10000) & (df['person_income'] < 50000)

1        False
2        False
3        False
4        False
5        False
         ...
44996     True
44997    False
44998    False
44999     True
45000    False
Length: 45000, dtype: bool

In [47]:
# a teraz dane
df[(df['loan_amnt'] > 10000) & (df['person_income'] < 50000)]

,person_age,person_education,person_gender,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
461,24.0,Associate,male,22684.0,0,OWN,13000.0,PERSONAL,7.88,0.57,3.0,640,No,1
494,23.0,Bachelor,male,43042.0,1,RENT,22250.0,DEBTCONSOLIDATION,12.69,0.52,3.0,678,No,1
536,22.0,High School,male,38473.0,0,RENT,21250.0,DEBTCONSOLIDATION,12.42,0.55,3.0,599,No,1
544,21.0,High School,male,42536.0,0,RENT,21000.0,VENTURE,12.53,0.49,4.0,687,No,1
547,26.0,Bachelor,female,48929.0,6,RENT,21000.0,MEDICAL,6.54,0.43,4.0,601,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44989,28.0,Associate,female,49170.0,4,RENT,10401.0,HOMEIMPROVEMENT,11.97,0.21,6.0,677,No,1
44992,24.0,High School,male,37786.0,0,MORTGAGE,13500.0,EDUCATION,13.43,0.36,4.0,612,No,1
44995,24.0,Associate,female,31924.0,2,RENT,12229.0,MEDICAL,10.70,0.38,4.0,678,No,1
44996,27.0,Associate,male,47971.0,6,RENT,15000.0,MEDICAL,15.66,0.31,3.0,645,No,1
44999,29.0,Bachelor,male,33164.0,4,RENT,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1

In [48]:
# a teraz dopełnienie tych danych poprzez wykorzystanie tego samego warunku oraz negacji
# został dodany dodatkowy nawias
df[~((df['loan_amnt'] > 10000) & (df['person_income'] < 50000))]

,person_age,person_education,person_gender,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
1,22.0,Master,female,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
2,21.0,High School,female,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
3,25.0,High School,female,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
4,23.0,Bachelor,female,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
5,24.0,Master,male,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44993,23.0,Bachelor,female,40925.0,0,RENT,9000.0,PERSONAL,11.01,0.22,4.0,487,No,1
44994,27.0,High School,female,35512.0,4,RENT,5000.0,PERSONAL,15.83,0.14,5.0,505,No,1
44997,37.0,Associate,female,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1
44998,33.0,Associate,male,56942.0,7,RENT,2771.0,DEBTCONSOLIDATION,10.02,0.05,10.0,668,No,1
45000,24.0,High School,male,51609.0,1,RENT,6665.0,DEBTCONSOLIDATION,17.05,0.13,3.0,628,No,1

In [49]:
# jeżeli chcemy odfiltrować kolumnę na podstawie wielu wartości bardziej użyteczne i zwięzłe będzie
# wykorzystanie metody isin()
df['person_education'].isin(['Associate', 'High School'])

1        False
2         True
3         True
4        False
5        False
         ...
44996     True
44997     True
44998     True
44999    False
45000     True
Name: person_education, Length: 45000, dtype: bool

In [50]:
# filtrowanie jest również możliwe przy wykorzystaniu obiektu callalbe (wywoływalnego),
# np. funkcji wbudowanej lub funkcji anonimowej (lambdy)
# oto przykłady

# tu następuje odwołanie do wartość str z tej serii, następnie użycie metody startswith('D') na każdej
# wartości tej serii, co zwraca tablicę boolowską
map_1 = df['loan_intent'].str.startswith('D')

# tutaj ten sam efekt, ale z wykorzystaniem apply (mapuje coś na każdy element obiektu iterowalnego) - tu mapujemy funkcję
# na każdą wartość z danej serii danych, dodatkowo przekazujemy argument 'D' do tej funkjci mapowanej
map_2 = df['loan_intent'].apply(str.startswith, args='D')

# i kolejny przypadek z wykorzystaniem map oraz funkcji anonimowej
map_3 = df['loan_intent'].map(lambda x: x.startswith('D'))

map_1, map_2, map_3

(1        False
 2        False
 3        False
 4        False
 5        False
          ...
 44996    False
 44997    False
 44998     True
 44999    False
 45000     True
 Name: loan_intent, Length: 45000, dtype: bool,
 1        False
 2        False
 3        False
 4        False
 5        False
          ...
 44996    False
 44997    False
 44998     True
 44999    False
 45000     True
 Name: loan_intent, Length: 45000, dtype: bool,
 1        False
 2        False
 3        False
 4        False
 5        False
          ...
 44996    False
 44997    False
 44998     True
 44999    False
 45000     True
 Name: loan_intent, Length: 45000, dtype: bool)

In [51]:
# przyjmijmy scenariusz, w którym interesują nas rekordy, gdzie po odjęciu wartości
# pożyczki od dochodów pozostaje kwota > 50000

# możemy to obliczyć dość łatwo
print(df['person_income'] - df['loan_amnt'])

# teraz można na to nałożyć filtr
netto_income_mapping = (df['person_income'] - df['loan_amnt']) > 50000
print(netto_income_mapping)

# i przyłożyć do danych
df[netto_income_mapping]

# czy można to zrobić również z wykorzystaniem funkcji lambda?

# Funkcja lambda otrzymuje parametr dla każdej wartości zwracanej przez iterator dla obiektu iterowalnego
# na którym jest wywoływana. W poprzednim przypadku była to jedna seria danych więc do funkcji anonimowej trafiała
# pojedyncza wartość z serii. Teraz możemy spróbować z innym przykładem, gdzie do tej funkcji trafi więcej wartości.

# tutaj argumentem funkcji lambda jest cały rekord z ramki danych, możemy indeksować go w dowolny sposób
# który został przedstawiony wcześniej
df.apply(lambda x: (x['person_income'] - x['loan_amnt']) > 50000, axis=1)

1        36948.0
2        11282.0
3         6938.0
4        44753.0
5        31135.0
          ...
44996    32971.0
44997    56800.0
44998    54171.0
44999    21164.0
45000    44944.0
Length: 45000, dtype: float64
1        False
2        False
3        False
4        False
5        False
         ...
44996    False
44997     True
44998     True
44999    False
45000    False
Length: 45000, dtype: bool

1        False
2        False
3        False
4        False
5        False
         ...
44996    False
44997     True
44998     True
44999    False
45000    False
Length: 45000, dtype: bool

## 1.3 Wykorzystanie DataFrame.query

Oprócz przykładów zaprezentowanych powyżej istnieje również metoda `query`, której wykorzystanie przy filtrach o dużej liczbie elemementów może być prostsze w zapisie.

Przykłady w dokumentacji: https://pandas.pydata.org/docs/user_guide/indexing.html#the-query-method

Poniżej kilka przykładów.

In [52]:
df.query('person_income > 100000')

,person_age,person_education,person_gender,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
9,24.0,Associate,female,100684.0,3,RENT,35000.0,PERSONAL,8.90,0.35,2.0,544,No,1
11,22.0,High School,female,102985.0,0,RENT,35000.0,VENTURE,10.37,0.34,4.0,621,No,1
13,23.0,Bachelor,male,114860.0,3,RENT,35000.0,VENTURE,7.90,0.30,2.0,573,No,1
14,26.0,Master,male,130713.0,0,RENT,35000.0,EDUCATION,18.39,0.27,4.0,708,No,1
15,23.0,Associate,female,138998.0,0,RENT,35000.0,EDUCATION,7.90,0.25,4.0,583,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44948,42.0,Doctorate,male,705960.0,21,MORTGAGE,20686.0,PERSONAL,10.74,0.03,16.0,689,No,1
44966,31.0,Associate,male,100407.0,9,RENT,17783.0,VENTURE,19.80,0.18,8.0,655,No,1
44973,43.0,Associate,male,184295.0,20,MORTGAGE,25000.0,EDUCATION,20.00,0.14,15.0,720,No,1
44983,26.0,Bachelor,male,130495.0,0,RENT,7622.0,PERSONAL,15.58,0.06,5.0,609,No,1
44991,31.0,Master,male,136832.0,9,RENT,12319.0,PERSONAL,16.92,0.09,7.0,722,No,1

In [53]:
# tutaj również możemy używać łączników &, | oraz ~
display(df.query('person_education == "Doctorate" & person_age > 40'))
# poniższe działa jak isin(["Doctorate", "Master"])
df.query('person_education == ["Doctorate", "Master"] & person_age > 40')

,person_age,person_education,person_gender,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
29160,41.0,Doctorate,female,301153.0,21,MORTGAGE,5000.0,EDUCATION,9.99,0.02,12.0,721,No,0
29207,42.0,Doctorate,male,18097.0,19,OWN,3500.0,MEDICAL,11.01,0.19,11.0,569,No,1
29272,41.0,Doctorate,male,72894.0,17,RENT,23800.0,HOMEIMPROVEMENT,6.91,0.33,15.0,755,No,1
29282,42.0,Doctorate,male,99557.0,18,RENT,22000.0,DEBTCONSOLIDATION,10.99,0.22,12.0,608,Yes,0
29302,45.0,Doctorate,male,45165.0,25,RENT,20000.0,HOMEIMPROVEMENT,11.71,0.44,15.0,579,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43925,41.0,Doctorate,male,119343.0,19,MORTGAGE,7663.0,MEDICAL,15.13,0.06,13.0,709,No,1
44098,43.0,Doctorate,male,38812.0,16,RENT,8746.0,MEDICAL,15.62,0.23,9.0,722,No,1
44628,47.0,Doctorate,male,70131.0,22,RENT,1500.0,MEDICAL,16.17,0.02,22.0,735,No,1
44699,43.0,Doctorate,female,72213.0,21,MORTGAGE,15000.0,PERSONAL,11.01,0.21,14.0,726,No,1
44948,42.0,Doctorate,male,705960.0,21,MORTGAGE,20686.0,PERSONAL,10.74,0.03,16.0,689,No,1

,person_age,person_education,person_gender,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
29125,45.0,Master,male,96924.0,25,RENT,35000.0,MEDICAL,11.01,0.36,13.0,566,No,1
29132,43.0,Master,female,600812.0,22,MORTGAGE,25000.0,VENTURE,12.61,0.04,14.0,685,No,0
29138,43.0,Master,female,480854.0,20,MORTGAGE,28000.0,VENTURE,9.91,0.06,11.0,619,No,0
29154,41.0,Master,female,322597.0,18,MORTGAGE,24000.0,PERSONAL,10.37,0.07,11.0,683,Yes,0
29160,41.0,Doctorate,female,301153.0,21,MORTGAGE,5000.0,EDUCATION,9.99,0.02,12.0,721,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44543,48.0,Master,female,65958.0,24,RENT,1169.0,DEBTCONSOLIDATION,14.14,0.02,21.0,704,No,1
44628,47.0,Doctorate,male,70131.0,22,RENT,1500.0,MEDICAL,16.17,0.02,22.0,735,No,1
44659,44.0,Master,female,21702.0,19,RENT,1500.0,PERSONAL,11.21,0.07,12.0,767,No,1
44699,43.0,Doctorate,female,72213.0,21,MORTGAGE,15000.0,PERSONAL,11.01,0.21,14.0,726,No,1
44948,42.0,Doctorate,male,705960.0,21,MORTGAGE,20686.0,PERSONAL,10.74,0.03,16.0,689,No,1

## Zadania

1. Zamień nazwę kolumny `loan_amnt` na `loan_amount`.

2. Z ramki danych wykorzystanej w przykładach (loan) wyświetl:
* a) tylko kolumny 'person_gender', 'person_age' oraz 'person_income',
* b) wiersze od 1000 do 2000 włącznie (chodzi o kolejne wiersze w ramce, a nie wartość indeksu),
* c) wiersze parzyste,
* d) wiersze o parzystej wartości w kolumnie indeks,
* e) pierwszą i ostatnią kolumnę.

3. Z tej samej ramki danych wyświetl dane wykorzystując filtry oparte o mapowanie:
* a) tylko kobiety z wykształceniem 'Master' oraz 'Bachelor' i pożyczkami pomiędzy 50000 a 70000,
* b) wszyscy mężczyźni z wykształceniem innym niż 'Master' oraz będący właścicielem lokalu (kolumna person_home_ownership = OWN),
* c) wszystkie osoby z wartością `loan_percent_income` w przedziale od 0.4 do 0.6,
* d) wszystkie wartości pożyczek, których kwota jest wielokrotnością liczby 10000.

Zad 1

In [63]:
df.rename(columns={'loan_amnt': 'loan_amount'}, inplace=True)
df.head()

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amount,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,21.0,female,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

Zad 2

In [64]:
display ( df[['person_gender', 'person_age', 'person_income']] )

display ( df.iloc[1000:2001] )

display ( df[::2] )

display ( df[df.index % 2 == 0] )

display ( df.iloc[:, [0,-1]] )

      person_gender  person_age  person_income
0            female        22.0        71948.0
1            female        21.0        12282.0
2            female        25.0        12438.0
3            female        23.0        79753.0
4              male        24.0        66135.0
...             ...         ...            ...
44995          male        27.0        47971.0
44996        female        37.0        65800.0
44997          male        33.0        56942.0
44998          male        29.0        33164.0
44999          male        24.0        51609.0

[45000 rows x 3 columns]

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amount,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
1000,23.0,male,Bachelor,30059.0,0,MORTGAGE,1375.0,MEDICAL,11.11,0.05,4.0,506,No,1
1001,24.0,male,Bachelor,68258.0,2,RENT,18000.0,EDUCATION,13.48,0.26,3.0,671,No,1
1002,21.0,male,Bachelor,60821.0,0,RENT,18000.0,EDUCATION,14.74,0.30,2.0,530,No,1
1003,25.0,male,High School,70432.0,6,RENT,18000.0,VENTURE,11.01,0.26,4.0,609,No,1
1004,21.0,female,Bachelor,63842.0,0,RENT,18000.0,MEDICAL,19.69,0.28,2.0,678,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1996,21.0,male,Master,37264.0,0,RENT,14000.0,MEDICAL,10.65,0.38,2.0,545,No,1
1997,24.0,female,Associate,36841.0,4,RENT,14000.0,DEBTCONSOLIDATION,7.90,0.38,2.0,538,No,1
1998,24.0,male,Bachelor,37068.0,2,MORTGAGE,3075.0,DEBTCONSOLIDATION,11.01,0.08,4.0,521,Yes,0
1999,22.0,male,Bachelor,37513.0,0,RENT,14000.0,VENTURE,6.99,0.37,4.0,595,No,1
2000,23.0,female,Associate,36711.0,0,RENT,14000.0,MEDICAL,11.26,0.38,3.0,554,No,1

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amount,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
6,26.0,female,Bachelor,93471.0,1,RENT,35000.0,EDUCATION,12.42,0.37,3.0,701,No,1
8,24.0,female,Associate,100684.0,3,RENT,35000.0,PERSONAL,8.90,0.35,2.0,544,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44990,31.0,male,Master,136832.0,9,RENT,12319.0,PERSONAL,16.92,0.09,7.0,722,No,1
44992,23.0,female,Bachelor,40925.0,0,RENT,9000.0,PERSONAL,11.01,0.22,4.0,487,No,1
44994,24.0,female,Associate,31924.0,2,RENT,12229.0,MEDICAL,10.70,0.38,4.0,678,No,1
44996,37.0,female,Associate,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1
44998,29.0,male,Bachelor,33164.0,4,RENT,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amount,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
6,26.0,female,Bachelor,93471.0,1,RENT,35000.0,EDUCATION,12.42,0.37,3.0,701,No,1
8,24.0,female,Associate,100684.0,3,RENT,35000.0,PERSONAL,8.90,0.35,2.0,544,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44990,31.0,male,Master,136832.0,9,RENT,12319.0,PERSONAL,16.92,0.09,7.0,722,No,1
44992,23.0,female,Bachelor,40925.0,0,RENT,9000.0,PERSONAL,11.01,0.22,4.0,487,No,1
44994,24.0,female,Associate,31924.0,2,RENT,12229.0,MEDICAL,10.70,0.38,4.0,678,No,1
44996,37.0,female,Associate,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1
44998,29.0,male,Bachelor,33164.0,4,RENT,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1

       person_age  loan_status
0            22.0            1
1            21.0            0
2            25.0            1
3            23.0            1
4            24.0            1
...           ...          ...
44995        27.0            1
44996        37.0            1
44997        33.0            1
44998        29.0            1
44999        24.0            1

[45000 rows x 2 columns]

Zad 3

In [65]:
print("a")
female_master_bachelor_loans = df[
    (df['person_gender'] == 'female') &
    (df['person_education'].isin(['Master', 'Bachelor'])) &
    (df['loan_amount'] > 50000) &
    (df['loan_amount'] < 70000)
]
display(female_master_bachelor_loans.head())

print("b")
male_not_master_own_home = df[
    (df['person_gender'] == 'male') &
    (~df['person_education'].isin(['Master'])) &
    (df['person_home_ownership'] == 'OWN')
]
display(male_not_master_own_home.head())

print("c")
loan_percent_income_range = df[
    (df['loan_percent_income'] >= 0.4) &
    (df['loan_percent_income'] <= 0.6)
]
display(loan_percent_income_range.head())

print("d")
loan_multiple_of_10000 = df[
    (df['loan_amount'] % 10000 == 0)
]
display(loan_multiple_of_10000.head())

a

Empty DataFrame
Columns: [person_age, person_gender, person_education, person_income, person_emp_exp, person_home_ownership, loan_amount, loan_intent, loan_int_rate, loan_percent_income, cb_person_cred_hist_length, credit_score, previous_loan_defaults_on_file, loan_status]
Index: []

b

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amount,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
27,23.0,male,High School,14293.0,0,OWN,1400.0,PERSONAL,9.32,0.10,3.0,607,No,0
30,21.0,male,High School,14858.0,0,OWN,2000.0,MEDICAL,11.12,0.13,3.0,589,No,1
35,21.0,male,Associate,15150.0,0,OWN,2500.0,EDUCATION,7.51,0.17,4.0,600,No,1
43,23.0,male,High School,361547.0,0,OWN,24250.0,EDUCATION,19.41,0.07,2.0,637,Yes,0
57,23.0,male,Bachelor,333399.0,1,OWN,35000.0,PERSONAL,11.01,0.10,4.0,609,No,0

c

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amount,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,22.0,female,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
2,25.0,female,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,23.0,female,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,24.0,male,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
22,22.0,female,Master,79255.0,0,RENT,34000.0,EDUCATION,17.58,0.43,4.0,691,No,1

d

,person_age,person_gender,person_education,person_income,person_emp_exp,person_home_ownership,loan_amount,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
15,23.0,female,Master,600891.0,5,MORTGAGE,30000.0,DEBTCONSOLIDATION,10.65,0.05,3.0,670,Yes,0
36,22.0,female,Bachelor,58868.0,0,RENT,30000.0,EDUCATION,18.39,0.51,2.0,606,No,1
37,24.0,male,High School,78026.0,3,RENT,30000.0,DEBTCONSOLIDATION,14.54,0.38,3.0,582,No,1
38,25.0,male,Bachelor,90785.0,4,RENT,30000.0,HOMEIMPROVEMENT,16.89,0.33,4.0,649,No,1
39,23.0,female,High School,86811.0,0,RENT,30000.0,DEBTCONSOLIDATION,11.01,0.35,4.0,602,No,1